from pathlib import Path
from dataclasses import dataclass, field

# AI TOOLS! Do not edit this file manually.
# This file is auto-generated with path-tool. Do not edit manually.
# Generated from: pyproject.toml configuration
# run `.venv/bin/python project_paths_generate.py` to regenerate.

@dataclass
class ProjectPaths:
    """Runtime path resolver for Brave Profile Manager.
      This class wraps the path-tool generated paths and converts them to portable, runtime-resolved paths.
    """


    root: Path = field(default = Path('/home/lasse'))
    base_dir: Path = field(default = Path('/home/lasse/Documents/CoT_official'))
    loaders_core: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/core'))
    loaders_enrichers: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/enrichers'))
    loaders_validators: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/validators'))
    loaders_utils: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/utils'))
    loaders_scripts: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/scripts'))
    loaders_chunker: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/chunker'))
    loaders_embeddings: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/embeddings'))
    loaders_vector_store: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/vector_store'))
    loaders_tests: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/tests'))
    loaders_test_results: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/TEST_RUN_RESULTS'))
    loaders_test_results_after: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/TEST_RUN_RESULTS_AFTER_REORG'))
    loaders_docs: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/docs'))
    loaders_trash: Path = field(default = Path('/home/lasse/Documents/CoT_official/python-template-generator/loaders/TRASH'))
# properties
    brave_user_folder: Path = field(default = Path('/home/lasse/.config/BraveSoftware/Brave-Browser'))
    brave_avatar_dest_folder: Path = field(default = Path('/home/lasse/.config/BraveSoftware/Brave-Browser/Avatars'))
    brave_local_state_file_path: Path = field(default = Path('/home/lasse/.config/BraveSoftware/Brave-Browser/Local State'))
    brave_exe_file_path: Path = field(default = Path('/usr/bin/brave-browser'))